# Generated by Django 3.2.15 on 2022-09-02 19:09

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_id', models.CharField(max_length=5)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('delivery_date', models.DateField()),
                ('delivery_time', models.TimeField()),
                ('order_date_time', models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 3, 0, 39, 50, 457258))),
                ('address', models.CharField(max_length=100)),
                ('chicken_kg', models.CharField(max_length=10)),
                ('chicken_category', models.CharField(max_length=20)),
                ('chicken_citting', models.CharField(max_length=20)),
                ('mutton_kg', models.CharField(max_length=20)),
                ('mutton_category', models.CharField(max_length=20)),
                ('mutton_cutting', models.CharField(max_length=20)),
                ('status', models.BooleanField()),
                ('delivered', models.BooleanField()),
                ('amount', models.IntegerField(max_length=1000)),
                ('review', models.CharField(max_length=200)),
            ],
        ),
    ]
