# Generated by Django 3.2.15 on 2022-09-02 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='order_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 3, 0, 42, 30, 903879)),
        ),
    ]
