# Generated by Django 3.2.15 on 2022-09-16 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_ordermodel_order_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='current_date',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='order_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 16, 14, 43, 4, 271939)),
        ),
    ]
