# Generated by Django 3.2.15 on 2022-09-16 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220916_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_time', models.CharField(max_length=10)),
                ('order_date', models.CharField(max_length=10)),
                ('del_time', models.CharField(max_length=15)),
                ('del_date', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='order_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 16, 15, 50, 3, 606315)),
        ),
    ]
